### ISSUE TITLE
document proxy protocol using sequence diagram

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/proxy#104]
It would be useful to create a UML sequence diagram showing the message flows between the following:

- proxy
- shim
- runtime
- agent

**Comment by jcvenegas** [comment]
I followed the runtime flow to understand how a container is created in 3.0 and used mermaidjs (https://github.com/knsv/mermaid / https://mermaidjs.github.io/mermaid-live-editor) to generate a sequenceDiagram:
```
sequenceDiagram
Docker->> Runtime: Create
Runtime->> VirtContainers: CreatePod
VirtContainers->> Qemu: Start 
Qemu->>VirtContainers: Started
Qemu->>Agent: Start
Note right of Proxy: Started
VirtContainers->> Proxy: Connect
Proxy->> VirtContainers: Connected
VirtContainers->> Proxy: registerVM
Note right of Proxy: Wait for Agent ready
Agent->>Proxy: Ready
Proxy->>VirtContainers: Tokens
VirtContainers->> Shim: Start(token)
Shim->> Proxy: Connect(token)
Proxy->> Shim: Shim Connected
Shim->> VirtContainers: Started
```
Missing Cases:
- IO session messages - Write from process to shim (stdin,stdout, str)
- Exit Code
- Shim disconnected  

![image](https://user-images.githubusercontent.com/20407785/29429318-e8db5146-8355-11e7-9050-dc0dc6f5fdce.png)


*Note: I used mermaid  because I like that could modify the image, just by modifying the lines above*

**Comment by jodh-intel** [comment]
Nice! I hadn't heard of mermaid, but as long as we store the original text representation as well as the SVG, we can potentially also edit with http://plantuml.com/ which is also ascii-based and uses a similar syntax fwics.

Wanna convert this into a doc?

@grahamwhaley - any thoughts on this from a runtime architecture doc perspective?

**Comment by grahamwhaley** [comment]
I concur - v.nice @jcvenegas I think the use of the textual base and then mermaid is a good thing - all plain text, all open source. We should adopt this for some other diagrams in the docs.
Yes, it will be good to see this as (maybe part of a) PR to build the docs up - and yes, we should add the text and probably svg (think we have settled on svg as our picture format of choice here now).

**Comment by jcvenegas** [comment]
@jodh-intel @grahamwhaley tried planuml, they provide render in server as well, I love it, it generates  ascii-based diagrams.

```
@startuml
Docker -> Runtime: Create
Runtime -> VirtContainers: CreatePod
VirtContainers -> Qemu: Start 
Qemu -> VirtContainers: Started
Qemu --> Agent: Start
Note right of Proxy: Started
VirtContainers ->  Proxy: Connect
Proxy --> VirtContainers: Connected
VirtContainers -> Proxy: registerVM
Note right of Proxy: Wait for Agent ready
Agent -> Proxy: Ready
Proxy --> VirtContainers: Tokens
VirtContainers -> Shim: Start(token)
Shim -> Proxy: Connect(token)
Proxy --> Shim: Shim Connected
Shim --> VirtContainers: Started
@enduml
```
     ┌──────┐          ┌───────┐          ┌──────────────┐          ┌────┐          ┌─────┐          ┌─────┐          ┌────┐      
     │Docker│          │Runtime│          │VirtContainers│          │Qemu│          │Agent│          │Proxy│          │Shim│      
     └──┬───┘          └───┬───┘          └──────┬───────┘          └─┬──┘          └──┬──┘          └──┬──┘          └─┬──┘      
        │      Create      │                     │                    │                │                │               │         
        │ ────────────────>│                     │                    │                │                │               │         
        │                  │                     │                    │                │                │               │         
        │                  │     CreatePod       │                    │                │                │               │         
        │                  │────────────────────>│                    │                │                │               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │        Start       │                │                │               │         
        │                  │                     │ ───────────────────>                │                │               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │       Started      │                │                │               │         
        │                  │                     │ <───────────────────                │                │               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │     Start      │                │               │         
        │                  │                     │                    │  ─ ─ ─ ─ ─ ─ ─>│                │               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │                │                │ ╔═════════╗   │         
        │                  │                     │                    │                │                │ ║Started ░║   │         
        │                  │                     │                    │                │                │ ╚═════════╝   │         
        │                  │                     │                    │  Connect       │                │               │         
        │                  │                     │ ────────────────────────────────────────────────────>│               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │ Connected      │                │               │         
        │                  │                     │ <─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ │               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │ registerVM     │                │               │         
        │                  │                     │ ────────────────────────────────────────────────────>│               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │                │                │ ╔═════════════╧════════╗
        │                  │                     │                    │                │                │ ║Wait for Agent ready ░║
        │                  │                     │                    │                │                │ ╚═════════════╤════════╝
        │                  │                     │                    │                │     Ready      │               │         
        │                  │                     │                    │                │───────────────>│               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │   Tokens       │                │               │         
        │                  │                     │ <─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ │               │         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │        Start(token)             │               │         
        │                  │                     │ ─────────────────────────────────────────────────────────────────────>         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │                │                │Connect(token) │         
        │                  │                     │                    │                │                │<──────────────│         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │                │                │Shim Connected │         
        │                  │                     │                    │                │                │ ─ ─ ─ ─ ─ ─ ─>│         
        │                  │                     │                    │                │                │               │         
        │                  │                     │                    │           Started               │               │         
        │                  │                     │ <─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─         
     ┌──┴───┐          ┌───┴───┐          ┌──────┴───────┐          ┌─┴──┐          ┌──┴──┐          ┌──┴──┐          ┌─┴──┐      
     │Docker│          │Runtime│          │VirtContainers│          │Qemu│          │Agent│          │Proxy│          │Shim│      
     └──────┘          └───────┘          └──────────────┘          └────┘          └─────┘          └─────┘          └────┘

**Comment by egernst** [comment]
who's the right person to document this?

**Comment by gorozco1** [comment]
@egernst my guess is @amshinde and probably @jcvenegas

**Comment by amshinde** [comment]
this was on my todo list for the next couple of days, but looks like @jcvenegas has already started on this.
@jcvenegas If you working on this please assign it to yourself.

**Comment by jcvenegas** [comment]
@amshinde yes, I can send the a PR with the `create` workflow.
