### ISSUE TITLE
Proxy should forbid newcontainer/execcmd if no shim is associated with the corresponding I/O token

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/proxy#21]
When newcontainer/execcmd hyperstart commands are issued, they start a process that send data on stdout/err. The proxy needs to do something with that data, namely send it to the corresponding shim.

Now that the shim connection is explicit, it theoretically possible a runtime asks us to forward a newcontainer command without a shim associated with the I/O token. We have two ways to solve that:
- Queue the stdout/err data in the proxy until the shim associates
- Require that a shim fully setup before we accept a newcontainer command

The second option is the one that requires the least amount of work and is also quite logical after all: don't start the process before the I/O path is fully up. Flow should go:

- **create**
  1. runtime asks for an I/O token with RegisterVM/AttachVM
  2. runtime creates shim process with Token
  3. shim issues a ConnectShim command with the Token
- **start**
  1. runtime issues newcontainer command

Things are a bit more fuzzy for execcmd as the runtime needs to know when the shim is associated. This could be fixed by the shim telling the runtime it's ready and the runtime would wait for that before doing an execcmd.

**Comment by sameo** [comment]
@dlespiau @sboeuf For exec, either we unconditionally accept `execcmd` commands from the proxy and queue them until a shim for it shows up, or we return a `EAGAIN` to the runtime if the shim is not there yet.

The 2nd option will allow us to support crashing shims. The runtime would give up or try to recover after a few tries.

**Comment by sboeuf** [comment]
@sameo your second option does not work with virtcontainers. The runtime calls virtcontainers to do this execcmd, and it expects this to work so that it can give the token back to the runtime. Then the runtime starts the shim with the token previously retrieved. That means that you're creating a deadlock by introducing EAGAIN, am I right ?

**Comment by amshinde** [comment]
@dlespiau I like the option of the runtime starting the shim before issuing the execcmd, that simplifies things in my opinion.

I would also like to point out that in the create-start sequence, the shim needs to be paused before it starts reading the stdin/out streams as that should happen only in start. See: https://github.com/clearcontainers/shim/issues/9
