### ISSUE TITLE
Explore gometalinter to replace our own set of shell scripts

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/proxy#45]
The fewer things we have to maintain the better. While I wrote custom scripts to make sure we don't regress on goreport, it may be a good idea to replace them by gometalinter. Careful to not overdo it and introduce awkward checkers that make us bend backwards to eliminate unhelpful warnings.

**Comment by sameo** [comment]
See https://github.com/kubernetes-incubator/cri-o/blob/master/.tool/lint
