### ISSUE TITLE
Signal should be passed with the container ID

### ISSUE THREAD

**Issue by sboeuf** [clearcontainers/proxy#71]
In case the shim receive a signal and call into the proxy to handle this signal, the proxy should not signal the session.vm.containerID. Instead, there are two options:
- The shim can give the container ID
OR
- Every session holds a container ID

This is needed for the case where the podID is different from the the containerID.

**Comment by sboeuf** [comment]
@sameo @dlespiau This issue is the reason why https://github.com/clearcontainers/runtime/pull/147 CI is currently failing. indeed, we don't have "real" support for podID and several containerIDs from a proxy perspective.

**Comment by dlespiau** [comment]
Oh, that was fixed! Closing.
